name: Build pull request

on:
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    permissions:
      checks: write
      contents: read
    uses: 'connectorio/gh-actions-shared/.github/workflows/maven.yml@master'
    secrets: inherit
    with:
      openhab: true
      server_id: sonatype-central
